version: '2'
services:
  postgres-rastro:
        image: postgres:14
        container_name: postgres-aba
        restart: always
        ports:
          - 5437:5432
        networks:
          - aba-network
        environment:
          POSTGRES_USER: aba
          POSTGRES_PASSWORD: aba
          PGDATA: /var/lib/postgresql/data/pgdata       
        volumes:
            - ./pgdata:/var/lib/postgresql/data      
        logging:
            driver: "json-file"
            options:
                max-size: "100m"   
  
networks:
  aba-network:
    driver: bridge
